{
 "title": "Hasura Logs & Traces",
 "description": "View Hasura Logs and Traces",
 "tags": [ "hasura" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki", "query": "loki" },
   { "name": "DS_JAEGER", "label": "Jaeger", "query": "jaeger" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   { "name": "search_keyword", "label": "Search" },
   {
    "name": "log_type",
    "label": "Type",
    "query": "startup,http-log,websocket-log,event-trigger,webhook-log,query-log,livequery-poller-log"
   },
   { "name": "trace_id", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Hasura Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\"} |~ `(?i)$search_keyword` | json | type =~ `$log_type`"
    }
   ]
  },
  {
   "title": "Trace Detail",
   "type": "traces",
   "description": "Paste the Trace ID to search the trace",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "query": "$trace_id" }
   ]
  },
  {
   "title": "Hasura Logs by OTEL",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\",job=\"hasura\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Hasura Logs by OTEL (with JSON parsed)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", job=\"hasura\"} | json",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}