{
 "title": "Hasura Subscriptions",
 "description": "Hasura subscription dashboards",
 "tags": [ "hasura" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "query_hash",
    "label": "Query Hash",
    "query": {
     "query": "label_values(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\"},parameterized_query_hash)"
    }
   },
   {
    "name": "operation_name",
    "label": "Operation Name",
    "query": {
     "query": "label_values(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",parameterized_query_hash=~\"$query_hash\"},operation_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WS Egress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operation_name) (hasura_websocket_messages_sent_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Subscriptions",
   "type": "gauge",
   "description": "Current number of active subscriptions",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"})"
    }
   ]
  },
  {
   "title": "Subscription Latency (P95)",
   "type": "stat",
   "description": "P95 latency of active subscriptions",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Websocket Connections",
   "type": "gauge",
   "description": "Current number of active WebSocket connections",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_websocket_connections{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Subscription Pollers",
   "type": "gauge",
   "description": "Current number of active Subscription Pollers",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_active_subscription_pollers{job=~\"$job\",subscription_kind=\"live-query\"})"
    }
   ]
  },
  {
   "title": "Active Streaming Requests",
   "type": "gauge",
   "description": "Current number of active streaming requests",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"})"
    }
   ]
  },
  {
   "title": "Streaming Latency (P95)",
   "type": "stat",
   "description": "P95 latency of active streaming requests",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Top Active Subscriptions / Streamings",
   "type": "table",
   "description": "Top active subscription and streaming requests count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, sum by (operation_name,parameterized_query_hash,subscription_kind) (hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"})) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Latency (P95)",
   "type": "table",
   "description": "Top latency of active subscriptions and stream requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__range])) by (operation_name,parameterized_query_hash,subscription_kind,le)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gereral Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Hasura Websocket Connections",
   "type": "timeseries",
   "description": "Current number of active WebSocket connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (hasura_websocket_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Queue Latency (P95)",
   "type": "timeseries",
   "description": "The time for which a websocket message remains queued in the GraphQL engine's websocket queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_websocket_message_queue_time_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (job,instance,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Subscription Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active Subscriptions",
   "type": "timeseries",
   "description": "Current number of active subscriptions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (operation_name, parameterized_query_hash) (hasura_active_subscriptions{subscription_kind=\"live-query\",job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscription Latency (P95)",
   "type": "timeseries",
   "description": "Time taken to compelete the running of one subscription poller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__rate_interval])) by (parameterized_query_hash,operation_name,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Subscription Pollers",
   "type": "timeseries",
   "description": "Current active number of subscription pollers running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (job, instance) (hasura_active_subscription_pollers{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscription DB Exec Latency (P95)",
   "type": "timeseries",
   "description": "Time taken in seconds to run the subscription's multiplexed query in the database of a single batch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_db_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__rate_interval])) by (parameterized_query_hash,operation_name,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscription Pollers in Error State",
   "type": "timeseries",
   "description": "Current active number of subscription pollers in the error state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (job, instance) (hasura_active_subscription_pollers_in_error_state{subscription_kind=\"live-query\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Streaming Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Active Streamings",
   "type": "timeseries",
   "description": "Current number of active streaming requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (operation_name, parameterized_query_hash) (hasura_active_subscriptions{subscription_kind=\"streaming\",job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streaming Latency (P95)",
   "type": "timeseries",
   "description": "P95 streaming latency of Hasura instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__rate_interval])) by (parameterized_query_hash,operation_name,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Streaming Pollers",
   "type": "timeseries",
   "description": "Current active number of subscription pollers running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum  by (job, instance) (hasura_active_subscription_pollers{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streaming DB Exec Latency (P95)",
   "type": "timeseries",
   "description": "Time taken in seconds to run the streaming's multiplexed query in the database of a single batch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_db_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__rate_interval])) by (parameterized_query_hash,operation_name,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streaming Pollers in Error State",
   "type": "timeseries",
   "description": "Current active number of streaming pollers in the error state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (instance, job) (hasura_active_subscription_pollers_in_error_state{subscription_kind=\"streaming\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}