{
 "title": "Hasura Query Level Metrics",
 "tags": [ "hasura" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Query-level metrics with operation name (A)",
   "type": "timeseries",
   "description": "This grafana board does not require operationName field to be present inside query-log.\n\nIt uses pattern expression matching to extract the operation_name from query string",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({job=\"hasura\"} |= `query-log` | pattern `<_>\"query <queryName> <_>` | queryName != `` [1m])",
     "legendFormat": "{{queryName}}"
    }
   ]
  },
  {
   "title": "HGE Logs 2 (Not-For-Use)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({instance=\"hge\"} |= `query-log` | pattern `<_>\"query <queryName> <_>` | queryName != `''` [1m])",
     "legendFormat": "{{queryName}}"
    }
   ]
  },
  {
   "title": "Query-level Metrics with operation name (B)",
   "type": "timeseries",
   "description": "This board displays query level metrics separated by query names. \n\nIt requires operationName field to be present in query-log",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({instance=\"hge\"} |= `query-log` | json operation=\"detail.query.operationName\" | operation != `` [1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "HGE Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{instance=\"hge\", job=\"graphql-engine\"} |= `query` | json"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {}
   ]
  }
 ]
}